### ISSUE TITLE
Homepage: Move "United States" Image & Caption

### ISSUE THREAD

**Issue by brendonsanctuary** [sanctuarycomputer/negative#37]
If we can move this image farther to the left. 

<img width="2006" alt="Screen Shot 2020-07-21 at 12 12 04 PM" src="https://user-images.githubusercontent.com/58054507/88079270-77232880-cb4b-11ea-8720-b4630600f688.png">

**Comment by chrismekim** [comment]
How much farther to the left? Right now I think the design show it's a col-3 and offset by a col-3 on the left. (In the code it's a col-6 and offset by a col-6 because I have each image in a div, and each div takes up a col-6 of the site width) ![Screen Shot 2020-07-21 at 11 53 15 AM](https://user-images.githubusercontent.com/43737723/88083584-3c23f380-cb51-11ea-85d1-1684085cb033.png)

**Comment by brendonsanctuary** [comment]
in the designs col-3 offset by a col-2 on the left.

**Comment by chrismekim** [comment]
@brendonsanctuary Ahh I realized I was looking at the "Designs" section where it's still offset by a col-3! Added to #36
